// This code was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
namespace net.r_eg.LunaRoad
{
    // TODO: it can be as here - vssbe.r-eg.net/doc/Examples/Version
    // but currently I don't want to change this, because it will be automatically changed if plugin exists (use .version)
    internal struct LunaRoadVersion
    {
        public const string numberString = "0.1.0";
    }
}
